from __future__ import annotations

import json
import logging
import os
from pathlib import Path
from typing import Any

import requests


RuntimeConfig = dict[str, Any]


def load_runtime_config(root_dir: str | Path) -> RuntimeConfig:
    """Load optional user-managed runtime config.

    Precedence:
    1. RUNTIME_CONFIG_JSON
    2. RUNTIME_CONFIG_PATH
    3. RUNTIME_CONFIG_PROVIDER=supabase

    The committed YAML config remains the default source of truth when no
    runtime config is configured or the remote config cannot be read.
    """

    logger = logging.getLogger("jarvis.runtime_config")
    inline = os.getenv("RUNTIME_CONFIG_JSON")
    if inline:
        return _parse_json(inline, "RUNTIME_CONFIG_JSON", logger)

    config_path = os.getenv("RUNTIME_CONFIG_PATH")
    if config_path:
        path = Path(config_path)
        if not path.is_absolute():
            path = Path(root_dir) / path
        try:
            return _parse_json(path.read_text(encoding="utf-8"), str(path), logger)
        except OSError as exc:
            logger.warning("Runtime config file could not be read; using YAML defaults: %s", exc)
            return {}

    if (os.getenv("RUNTIME_CONFIG_PROVIDER") or "").lower() == "supabase":
        return _load_supabase_runtime_config(logger)

    return {}


def merge_runtime_config(defaults: RuntimeConfig, runtime: RuntimeConfig) -> RuntimeConfig:
    """Merge runtime config over YAML defaults.

    Runtime configs generated by the PWA are full documents, but this merge also
    supports partial overrides so small hand-authored JSON secrets remain useful.
    """

    if not runtime:
        return defaults

    merged: RuntimeConfig = {
        "agent": {**dict(defaults.get("agent") or {})},
        "topics": dict(defaults.get("topics") or {}),
        "sources": list(defaults.get("sources") or []),
        "trust_rules": dict(defaults.get("trust_rules") or {}),
    }

    if isinstance(runtime.get("agent"), dict):
        merged["agent"] = {**merged["agent"], **runtime["agent"]}

    if isinstance(runtime.get("topics"), dict):
        merged["topics"] = _merge_mapping(merged["topics"], runtime["topics"])

    if isinstance(runtime.get("sources"), list):
        merged["sources"] = runtime["sources"]

    if isinstance(runtime.get("trust_rules"), dict):
        merged["trust_rules"] = _deep_merge(merged["trust_rules"], runtime["trust_rules"])

    return merged


def _parse_json(raw: str, source_name: str, logger: logging.Logger) -> RuntimeConfig:
    try:
        payload = json.loads(raw)
    except json.JSONDecodeError as exc:
        logger.warning("Runtime config JSON is invalid in %s; using YAML defaults: %s", source_name, exc)
        return {}
    if not isinstance(payload, dict):
        logger.warning("Runtime config in %s must be a JSON object; using YAML defaults", source_name)
        return {}
    return payload


def _load_supabase_runtime_config(logger: logging.Logger) -> RuntimeConfig:
    url = (os.getenv("SUPABASE_URL") or "").rstrip("/")
    key = os.getenv("SUPABASE_SERVICE_ROLE_KEY")
    config_id = os.getenv("RUNTIME_CONFIG_ID") or "active"
    if not url or not key:
        logger.warning("Supabase runtime config selected but Supabase credentials are missing")
        return {}

    try:
        response = requests.get(
            f"{url}/rest/v1/runtime_configs",
            headers={"apikey": key, "Authorization": f"Bearer {key}"},
            params={
                "select": "config",
                "config_id": f"eq.{config_id}",
                "is_active": "eq.true",
                "order": "updated_at.desc",
                "limit": "1",
            },
            timeout=15,
        )
        response.raise_for_status()
        rows = response.json()
    except Exception as exc:
        logger.warning("Supabase runtime config could not be loaded; using YAML defaults: %s", exc)
        return {}

    if not rows:
        logger.info("No active Supabase runtime config found for id %s; using YAML defaults", config_id)
        return {}

    config = rows[0].get("config")
    if not isinstance(config, dict):
        logger.warning("Supabase runtime config row has invalid config payload; using YAML defaults")
        return {}
    return config


def _merge_mapping(defaults: dict[str, Any], runtime: dict[str, Any]) -> dict[str, Any]:
    merged = {**defaults}
    for key, value in runtime.items():
        if isinstance(value, dict) and isinstance(merged.get(key), dict):
            merged[key] = _deep_merge(merged[key], value)
        else:
            merged[key] = value
    return merged


def _deep_merge(defaults: dict[str, Any], runtime: dict[str, Any]) -> dict[str, Any]:
    merged = {**defaults}
    for key, value in runtime.items():
        if isinstance(value, dict) and isinstance(merged.get(key), dict):
            merged[key] = _deep_merge(merged[key], value)
        else:
            merged[key] = value
    return merged
